# migrate
FROM composer:2 AS migrate
WORKDIR /app

COPY composer.json composer.lock artisan ./
RUN composer install --no-interaction --no-autoloader

COPY app/ ./app/
COPY bootstrap/ ./bootstrap/
COPY config/ ./config/
COPY database/ ./database/
COPY resources/ ./resources/
COPY routes/ ./routes/
COPY public/ ./public/
COPY storage/ ./storage/

CMD ["php", "artisan", "migrate", "-n", "--force"]
